// Karina asked (8/27) to drop the visible "PLACEHOLDER TEXT" line so this reads clean for her
// team while they start testing tonight. Note this is still NOT lawyer-reviewed, verbatim
// proprietary-terms language — it's a reasonable working draft I wrote covering the points she'd
// mentioned (confidentiality, no competing use, client data ownership, revocable access, and
// "verify before you rely on it"). If she ever gets real legal text from counsel, drop it in here
// verbatim and bump TERMS_VERSION so everyone gets re-prompted to accept the real version.
//
// Bump TERMS_VERSION any time the wording changes — advisors who already accepted an older version
// will be prompted again automatically (the gate compares against profiles.terms_version).

export const TERMS_VERSION = "v3";

export const TERMS_TITLE = "Generational Playbook — Advisor Portal Terms";

export const TERMS_TEXT = `This portal, its Knowledge Base content, recommendation logic, and any generated materials are the
proprietary property of Generational Playbook and are provided to you solely for your use as an
authorized Generational Playbook advisor.

1. You will not copy, redistribute, or share access to this portal or its contents outside of
   Generational Playbook.
2. You will not use this portal's content, tools, or recommendations to build a competing
   platform or to train or supply any third-party system.
3. Client data you enter remains the property of Generational Playbook and must be handled in
   accordance with applicable privacy and insurance regulations.
4. Your access may be revoked at any time if you leave Generational Playbook or violate these
   terms.
5. Recommendations generated by this portal are aids for advisor judgment only, not verified
   advice. You must independently review and verify all information, calculations, and
   recommendations before relying on them or presenting them to a client — final suitability,
   compliance, and disclosure obligations remain your responsibility as the advisor.

By clicking "I Agree," you acknowledge that you have read and accept these terms.`;
