// ⚠️ PLACEHOLDER — Karina, this is the ONE thing in Phase 4 I could not port faithfully: I don't
// have the actual verbatim "Proprietary Technology Notice" text from the other conversation you
// referenced. I'm not willing to write real legal/proprietary terms language myself and pass it
// off as the real thing, so this is a clearly-labeled placeholder. Send me the exact text and I'll
// drop it in here verbatim — nothing else about the acceptance flow needs to change.
//
// Updated per Karina's request (8/26): switched "agent" -> "advisor" throughout to match the
// product's own branding ("GP Advisor Portal", the "Advisor" role label everyone actually sees),
// and strengthened #5 to explicitly tell advisors to independently verify everything the portal
// generates rather than relying on it — this is still placeholder wording pending her real text.
//
// Bump TERMS_VERSION any time the wording changes — advisors who already accepted an older version
// will be prompted again automatically (the gate compares against profiles.terms_version).

export const TERMS_VERSION = "v2-placeholder";

export const TERMS_TITLE = "Generational Playbook — Advisor Portal Terms";

export const TERMS_TEXT = `PLACEHOLDER TEXT — replace with the real, verbatim terms.

This portal, its Knowledge Base content, recommendation logic, and any generated materials are the
proprietary property of Generational Playbook and are provided to you solely for your use as an
authorized Generational Playbook advisor.

1. You will not copy, redistribute, or share access to this portal or its contents outside of
   Generational Playbook.
2. You will not use this portal's content, tools, or recommendations to build a competing
   platform or to train or supply any third-party system.
3. Client data you enter remains the property of Generational Playbook and must be handled in
   accordance with applicable privacy and insurance regulations.
4. Your access may be revoked at any time if you leave Generational Playbook or violate these
   terms.
5. Recommendations generated by this portal are aids for advisor judgment only, not verified
   advice. You must independently review and verify all information, calculations, and
   recommendations before relying on them or presenting them to a client — final suitability,
   compliance, and disclosure obligations remain your responsibility as the advisor.

By clicking "I Agree," you acknowledge that you have read and accept these terms.`;
